---
name: Publish Package FAST.Gate.Client
env:
  PFOLDER: FAST.Gate.Client
  PNAME: FAST.Gate.Client
on:
  push:
    tags:
      - v*
  workflow_dispatch: null
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x
            10.0.x
      - name: Restore dependencies
        run: dotnet restore ${{ env.PFOLDER }}/${{ env.PNAME }}.csproj
      - name: Build project
        run: dotnet build ${{ env.PFOLDER }}/${{ env.PNAME }}.csproj --configuration Release
          --no-restore
      - name: Pack NuGet package
        run: dotnet pack ${{ env.PFOLDER }}/${{ env.PNAME }}.csproj --configuration Release
          --no-build --output ./nuget
      - name: Publish package to NuGet.org
        run: dotnet nuget push ./nuget/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }}
          --source https://api.nuget.org/v3/index.json
